import { 
  FileAudio, 
  Languages, 
  Newspaper, 
  PenTool, 
  PieChart,
  Palette,
  FileCheck,
  Users,
  Search,
  Share2,
  Camera
} from 'lucide-react';
import { Tool } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'transcript-studio',
    name: 'TDS Transcript Studio',
    description: 'Advanced AI-powered audio transcription and analysis tool for interviews and press conferences.',
    url: 'https://tds-transcript-studio-873947818170.us-west1.run.app/',
    icon: FileAudio,
    category: 'Audio',
    tags: ['Transcription', 'Audio Analysis', 'Internal'],
  },
  {
    id: 'translator',
    name: 'TDS Bilingual Translator',
    description: 'Real-time bilingual translation service optimized for breaking news and cross-regional reporting.',
    url: 'http://103.118.19.98:9999/',
    icon: Languages,
    category: 'Translation',
    tags: ['Translation', 'Live', 'Internal Network'],
    httpWarning: true
  },
  {
    id: 'print-companion',
    name: 'TDS Print Companion',
    description: 'An AI assistant designed to aid print journalists with fact-checking, structuring, and reporting.',
    url: 'https://chatgpt.com/g/g-6763f0f348188191912531a383680086-tds-print-companion',
    icon: Newspaper,
    category: 'Reporting',
    tags: ['GPT-5', 'Reporting Aid', 'ChatGPT'],
  },
  {
    id: 'bangla-editorial',
    name: 'Bangla Editorial Pro',
    description: 'Specialized tool for polishing, editing, and refining Bangla editorial content to meet publication standards.',
    url: 'https://chatgpt.com/g/g-6758675489b0819199f551e33a4acacf-bangla-editorial-pro',
    icon: PenTool,
    category: 'Editorial',
    tags: ['Bangla', 'Editing', 'GPT-5'],
  },
  {
    id: 'subeditor',
    name: 'TDS Smart Subeditor',
    description: 'Intelligent subediting assistant for grammar correction, style consistency, and clarity improvements.',
    url: 'https://subeditor.vercel.app/',
    icon: FileCheck,
    category: 'Editorial',
    tags: ['Editing', 'Proofreading', 'Web App'],
  },
  {
    id: 'infograph',
    name: 'TDS Infograph Maker',
    description: 'Create interactive infographics with vector export capabilities for print and digital platforms.',
    url: 'https://infolatest.vercel.app/',
    icon: PieChart,
    category: 'Visuals',
    tags: ['Design', 'Vector', 'Data Viz'],
  },
  {
    id: 'illustration',
    name: 'TDS Illustration Gen',
    description: 'Generate custom editorial illustrations and visual assets tailored for news stories.',
    url: 'https://infogenius-for-newspaper-170700854221.us-west1.run.app/',
    icon: Palette,
    category: 'Visuals',
    tags: ['AI Art', 'Illustration', 'Creative'],
  },
  {
    id: 'image-insight',
    name: 'TDS Image Insight',
    description: 'Analyze images to generate accurate keywords, captions, and visual descriptions for archives.',
    url: 'https://chatgpt.com/g/g-60zmth8JT-tds-image-insight',
    icon: Camera,
    category: 'Visuals',
    tags: ['Photography', 'Metadata', 'ChatGPT'],
  },
  {
    id: 'seo-insight',
    name: 'TDS SEO Insight',
    description: 'Comprehensive keyword reporting and SEO strategy analysis for digital content optimization.',
    url: 'https://keywords.dailystar.press',
    icon: Search,
    category: 'Digital',
    tags: ['SEO', 'Keywords', 'Analytics'],
  },
  {
    id: 'social-post',
    name: 'Social Post Generator',
    description: 'Instantly generate engaging social media posts for all platforms from article summaries.',
    url: 'https://social-post-generator-latest-170700854221.us-west1.run.app/',
    icon: Share2,
    category: 'Digital',
    tags: ['Social Media', 'Marketing', 'Automation'],
  },
  {
    id: 'cv-screener-admin',
    name: 'TDS CV Screener (Pro)',
    description: 'Advanced HR screening tool with backend database management for recruitment processes.',
    url: 'https://cv-screener-bolt.vercel.app/',
    icon: Users,
    category: 'HR',
    tags: ['Recruitment', 'Admin', 'Database'],
  },
  {
    id: 'cv-screener-lite',
    name: 'TDS CV Screener (Lite)',
    description: 'Quick AI-powered CV analysis and candidate scoring for rapid initial screening.',
    url: 'https://cv-screen-ai.vercel.app/',
    icon: Users,
    category: 'HR',
    tags: ['Recruitment', 'Fast Track'],
  },
  {
    id: 'bengali-translator',
    name: 'Bengali News Translator',
    description: 'High-precision English to Bangla translation specialized for news terminology and tone.',
    url: 'https://chatgpt.com/g/g-SVeHDqba1-bengali-news-translator',
    icon: Languages,
    category: 'Translation',
    tags: ['English to Bangla', 'ChatGPT'],
  },
  {
    id: 'newstone-translator',
    name: 'Newstone Translator',
    description: 'Expert Bangla to English translation for adapting local news for global audiences.',
    url: 'https://chatgpt.com/g/g-cWuwsG8sK-newstone-translator',
    icon: Languages,
    category: 'Translation',
    tags: ['Bangla to English', 'ChatGPT'],
  },
];

export const APP_NAME = "The Daily Star AI Hub";
export const APP_TAGLINE = "Empowering Journalism with Artificial Intelligence";